version: '3.3'
services:
  web-wallet:
    image: web-wallet:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/wallet_db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_user_password
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped